### PR TITLE
Replaced path pose parameter with return value.

### LINKED ISSUE #123: `Controller::findPositionOnPlan()` should be refactored
`Controller::findPositionOnPlan()` should be refactored:
1. Its name suggests it only finds a position but it also sets member variable `distance_to_goal_`. It is incorrect (or at least odd) to only change the distance but not any other state (current plan index, etc). I propose we make this function const and do not set any data members. It should just do as the name suggests and find something. If required this value can be made part of the return value. (But perhaps it might be easy to calculate by the caller.)
2. Parameter `path_pose_idx` is an output parameter. I propose we change it to be part of the return value.
3. Parameter `controller_state` contains way too much state. Only the following members are used:
    - `last_visited_pose_index` is used as an output parameter. I propose we change it to be part of the return value.
    - `current_global_plan_index` is used as an in-/output parameter. I propose we split this into a pure input parameter and make the output part of the return value.

### PR DESCRIPTION
**Pull request by lewie-donckers**
Next PR to fix #123 .

Refactored `Controller::findPositionOnPlan()`: replaced `path_pose_idx` output parameter with (part of) the return value.

### CODE REVIEW

**Review by Rayman — APPROVED** [review]

File: include/path_tracking_pid/controller.hpp [hunk 1]
```diff
@@ -96,22 +96,21 @@ class Controller : private boost::noncopyable
     const geometry_msgs::Twist & steering_odom_twist,
     const std::vector<tf2::Transform> & global_plan);
 
+  /** Result of findPositionOnPlan(). */
+  struct FindPositionOnPlanResult
+  {
+    tf2::Transform position;
```
Comment (rokusottervanger) [inline include/path_tracking_pid/controller.hpp:102]: I'd rather see this member named `pose` instead of `position`, as it represents not only a position, but also the orientation of the projection onto the path (together, this is called the "pose"). Maybe this also implies that the function should be named `FindPoseOnPlan` or something. Does that make sense, @cesar-lopez-mar ?

**Review by rokusottervanger — CHANGES_REQUESTED** [review]
Other than the single comment, I approve!

File: include/path_tracking_pid/controller.hpp (hunk 1 above)
Comment (cesar-lopez-mar) [reply include/path_tracking_pid/controller.hpp:102]: Indeed, also the data type represents a pose indirectly, we use transforms because we use functions of tf2 objects to make operations on them. When track_base_link is false we do not use the orientation but the same data type is used.

Comment (lewie-donckers) [reply include/path_tracking_pid/controller.hpp:102]: Fixed in #144 to avoid merge conflicts in the PR train. Since the name was not changed yet, it could be considered just another refactor step.

Comment (rokusottervanger) [reply include/path_tracking_pid/controller.hpp:102]: Sounds fair enough

**Review by rokusottervanger — APPROVED** [review]

**Review by cesar-lopez-mar — APPROVED** [review]
